from pathlib import Path
import re

ROOT = Path(__file__).resolve().parent.parent.parent / "projects"


def slugify(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def create_app(name):
    slug = slugify(name)
    project = ROOT / slug

    (project / "src").mkdir(parents=True, exist_ok=True)
    (project / "tests").mkdir(exist_ok=True)
    (project / "config").mkdir(exist_ok=True)

    (project / "README.md").write_text(
        f"# {name}\n\n"
        f"Generated by Banker AI.\n"
    )

    (project / "src" / "main.py").write_text(
        f'''""" {name} generated by Banker AI. """\n\n
def main():
    print("Hello from {name}")


if __name__ == "__main__":
    main()
'''
    )

    (project / "tests" / "test_main.py").write_text(
        "def test_project_exists():\n"
        "    assert True\n"
    )

    (project / "config" / "project.json").write_text(
        '{\n'
        f'  "name": "{name}",\n'
        '  "generator": "Banker AI",\n'
        '  "language": "python"\n'
        '}\n'
    )

    return project
