from pathlib import Path
import re


def slugify(text):
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def generate_project(name, description):
    slug = slugify(name)
    root = Path("projects") / slug

    (root / "src").mkdir(parents=True, exist_ok=True)
    (root / "tests").mkdir(exist_ok=True)
    (root / "config").mkdir(exist_ok=True)

    (root / "README.md").write_text(
        f"# {name}\n\n"
        f"Generated by Banker AI.\n\n"
        f"## Description\n\n{description}\n"
    )

    (root / "src" / "main.py").write_text(
        f'''"""
{name}
Generated by Banker AI.
"""

DESCRIPTION = {description!r}


def main():
    print("{name}")
    print(DESCRIPTION)


if __name__ == "__main__":
    main()
'''
    )

    (root / "tests" / "test_main.py").write_text(
        "def test_generated_project():\n"
        "    assert True\n"
    )

    (root / "config" / "project.json").write_text(
        "{\n"
        f'  "name": {name!r},\n'
        f'  "description": {description!r},\n'
        '  "generator": "Banker AI",\n'
        '  "language": "python"\n'
        "}\n"
    )

    (root / "build.sh").write_text(
        "#!/data/data/com.termux/files/usr/bin/bash\n"
        "echo 'Banker AI building project...'\n"
        "python src/main.py\n"
    )

    return root
